import { FamilyAppData } from './types';

const getTodayDateStr = (offsetDays = 0) => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const defaultFamilyData: FamilyAppData = {
  children: [
    {
      id: 'child-1',
      name: 'Liam',
      avatar: '🎮',
      color: '#3b82f6', // blue
      totalPoints: 840,
      currentPoints: 460,
      dailyGoal: 100,
      streakDays: 6,
      lastActiveDate: getTodayDateStr(0),
      badge: 'Chore Champion',
      level: 4,
      monthlyAllowanceTarget: 30, // $30/month base allowance
      theme: 'fintech_hustle',
    },
    {
      id: 'child-2',
      name: 'Emma',
      avatar: '👧',
      color: '#ec4899', // pink
      totalPoints: 720,
      currentPoints: 390,
      dailyGoal: 80,
      streakDays: 4,
      lastActiveDate: getTodayDateStr(0),
      badge: 'Super Helper',
      level: 3,
      monthlyAllowanceTarget: 25, // $25/month base allowance
      theme: 'classic',
    },
    {
      id: 'child-3',
      name: 'Noah',
      avatar: '🧒',
      color: '#10b981', // emerald
      totalPoints: 490,
      currentPoints: 240,
      dailyGoal: 60,
      streakDays: 3,
      lastActiveDate: getTodayDateStr(-1),
      badge: 'Rising Star',
      level: 2,
      monthlyAllowanceTarget: 15, // $15/month base allowance
      theme: 'classic',
    },
  ],
  tasks: [
    {
      id: 'task-1',
      title: 'Make Bed',
      description: 'Straighten sheets, fluff pillows, make bedroom tidy',
      category: 'daily_routine',
      points: 0,
      icon: 'bed',
      frequency: 'daily',
      choreType: 'allowance',
    },
    {
      id: 'task-2',
      title: 'Brush Teeth (Morning & Night)',
      description: '2 full minutes with timer and floss',
      category: 'daily_routine',
      points: 0,
      icon: 'sparkles',
      frequency: 'daily',
      choreType: 'allowance',
    },
    {
      id: 'task-3',
      title: 'Clothes in Laundry Hamper',
      description: 'Put dirty clothes inside the hamper, not on the floor',
      category: 'daily_routine',
      points: 0,
      icon: 'shirt',
      frequency: 'daily',
      choreType: 'allowance',
    },
    {
      id: 'task-4',
      title: 'Pack School Backpack',
      description: 'Folders, books, lunch box, and water bottle ready',
      category: 'school_study',
      points: 0,
      icon: 'backpack',
      frequency: 'daily',
      choreType: 'allowance',
    },
    {
      id: 'task-5',
      title: '20 Mins of Reading',
      description: 'Read a book, comic, or chapter reader quietly',
      category: 'school_study',
      points: 30,
      icon: 'book-open',
      frequency: 'daily',
      choreType: 'bonus_points',
    },
    {
      id: 'task-6',
      title: 'Complete Homework',
      description: 'Finish all school assignments before dinner',
      category: 'school_study',
      points: 0,
      icon: 'check-circle-2',
      frequency: 'daily',
      choreType: 'allowance',
    },
    {
      id: 'task-7',
      title: 'Tidy Bedroom & Toys',
      description: 'Put toys in bins, clear floor, shelf neat',
      category: 'bedroom_home',
      points: 0,
      icon: 'box',
      frequency: 'daily',
      choreType: 'allowance',
    },
    {
      id: 'task-8',
      title: 'Unload the Dishwasher',
      description: 'Put plates, cups, and silverware in cabinets carefully',
      category: 'bedroom_home',
      points: 35,
      icon: 'utensils',
      frequency: 'anytime',
      choreType: 'both',
      assignedTo: ['child-1', 'child-2'], // Liam & Emma
    },
    {
      id: 'task-9',
      title: 'Take Out Trash & Recycling',
      description: 'Empty small cans, tie bags, and wheel out to bins',
      category: 'bedroom_home',
      points: 0,
      icon: 'trash-2',
      frequency: 'weekly',
      daysOfWeek: [3], // Every Wednesday
      intervalWeeks: 1,
      choreType: 'allowance',
      assignedTo: ['child-1'], // Liam only
    },
    {
      id: 'task-10',
      title: 'Feed Family Pet',
      description: 'Fill clean food bowl and fresh water',
      category: 'pet_care',
      points: 0,
      icon: 'heart-handshake',
      frequency: 'daily',
      choreType: 'allowance',
      assignedTo: ['child-2'], // Emma only
    },
    {
      id: 'task-11',
      title: 'Water Garden & Deep Clean Linens',
      description: 'Water patio garden and wash bedding/linens',
      category: 'yard_outdoor',
      points: 40,
      icon: 'flower-2',
      frequency: 'weekly',
      daysOfWeek: [5], // Every other Friday
      intervalWeeks: 2,
      scheduleStartDate: '2026-09-18',
      choreType: 'both',
      assignedTo: ['child-1'], // Liam
    },
    {
      id: 'task-12',
      title: 'Help Cook Dinner',
      description: 'Wash veggies, stir ingredients, or set the dining table',
      category: 'bonus',
      points: 40,
      icon: 'chef-hat',
      frequency: 'anytime',
      isBonus: true,
      choreType: 'bonus_points',
    },
    {
      id: 'task-13',
      title: 'Random Act of Kindness',
      description: 'Help a sibling, give a sincere compliment, or do an unasked good deed',
      category: 'kindness_habits',
      points: 30,
      icon: 'heart',
      frequency: 'anytime',
      isBonus: true,
      choreType: 'bonus_points',
    },
  ],
  logs: [
    {
      id: 'log-1',
      childId: 'child-1',
      taskId: 'task-1',
      taskTitle: 'Make Bed',
      pointsEarned: 0,
      completedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
      dateStr: getTodayDateStr(0),
      note: 'Done right after waking up',
      verifiedByParent: true,
    },
    {
      id: 'log-2',
      childId: 'child-1',
      taskId: 'task-2',
      taskTitle: 'Brush Teeth (Morning & Night)',
      pointsEarned: 0,
      completedAt: new Date(Date.now() - 3.5 * 3600 * 1000).toISOString(),
      dateStr: getTodayDateStr(0),
      verifiedByParent: true,
    },
    {
      id: 'log-3',
      childId: 'child-1',
      taskId: 'task-5',
      taskTitle: '20 Mins of Reading',
      pointsEarned: 30,
      completedAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
      dateStr: getTodayDateStr(0),
      note: 'Read chapter 3 of Percy Jackson',
      verifiedByParent: true,
    },
    {
      id: 'log-4',
      childId: 'child-2',
      taskId: 'task-1',
      taskTitle: 'Make Bed',
      pointsEarned: 0,
      completedAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
      dateStr: getTodayDateStr(0),
      verifiedByParent: true,
    },
    {
      id: 'log-5',
      childId: 'child-2',
      taskId: 'task-10',
      taskTitle: 'Feed Family Pet',
      pointsEarned: 0,
      completedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
      dateStr: getTodayDateStr(0),
      verifiedByParent: true,
    },
    {
      id: 'log-6',
      childId: 'child-3',
      taskId: 'task-1',
      taskTitle: 'Make Bed',
      pointsEarned: 0,
      completedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
      dateStr: getTodayDateStr(-1),
      verifiedByParent: true,
    },
  ],
  rewards: [
    {
      id: 'rew-1',
      title: '30 Mins Extra Screen Time',
      description: 'iPad, Nintendo Switch, or TV time after homework',
      pointsCost: 75,
      icon: 'tv',
      category: 'Entertainment',
    },
    {
      id: 'rew-2',
      title: 'Choose Tonight’s Movie',
      description: 'You pick the family movie and the couch snack',
      pointsCost: 120,
      icon: 'film',
      category: 'Privilege',
    },
    {
      id: 'rew-3',
      title: 'Ice Cream Parlor Outing',
      description: 'Trip to favorite ice cream shop for a double scoop with toppings',
      pointsCost: 250,
      icon: 'ice-cream',
      category: 'Treats',
    },
    {
      id: 'rew-4',
      title: 'Stay Up 30 Mins Late',
      description: 'Friday or weekend bedtime extension',
      pointsCost: 100,
      icon: 'moon',
      category: 'Privilege',
    },
    {
      id: 'rew-5',
      title: 'Pass: Skip One Chore',
      description: 'Redeem to skip one chore of your choice (except brushing teeth!)',
      pointsCost: 200,
      icon: 'sparkles',
      category: 'Privilege',
    },
    {
      id: 'rew-6',
      title: '$10 Toy or Book Store Pick',
      description: 'Trip to pick out a new toy, game, or book of choice',
      pointsCost: 500,
      icon: 'gift',
      category: 'Prizes',
    },
    {
      id: 'rew-7',
      title: 'Pizza Night Request',
      description: 'Choose pizza toppings or local restaurant for dinner',
      pointsCost: 350,
      icon: 'pizza',
      category: 'Treats',
    },
    {
      id: 'rew-8',
      title: 'Arcade / Trampoline Park Trip',
      description: 'Full afternoon of arcade gaming or trampoline jumping',
      pointsCost: 850,
      icon: 'trophy',
      category: 'Big Adventure',
    },
    {
      id: 'rew-9',
      title: 'Nintendo Switch Mario Kart Tournament',
      description: '1 hour uninterrupted Switch gaming with sibling or parent',
      pointsCost: 150,
      icon: 'gamepad',
      category: 'Special',
      assignedTo: ['child-1'],
    },
    {
      id: 'rew-10',
      title: 'New Watercolor & Sketchbook Kit',
      description: 'Pick out premium art pens and drawing pad at the store',
      pointsCost: 350,
      icon: 'gift',
      category: 'Creative',
      assignedTo: ['child-2'],
    },
    {
      id: 'rew-11',
      title: 'Trip to Indoor Playground / Dino Park',
      description: 'Special weekend morning playground climbing adventure',
      pointsCost: 200,
      icon: 'trophy',
      category: 'Outing',
      assignedTo: ['child-3'],
    },
  ],
  redemptions: [
    {
      id: 'red-1',
      childId: 'child-1',
      rewardId: 'rew-1',
      rewardTitle: '30 Mins Extra Screen Time',
      pointsSpent: 75,
      status: 'fulfilled',
      requestedAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
      resolvedAt: new Date(Date.now() - 47 * 3600 * 1000).toISOString(),
      parentNote: 'Enjoyed Mario Kart!',
    },
    {
      id: 'red-2',
      childId: 'child-2',
      rewardId: 'rew-4',
      rewardTitle: 'Stay Up 30 Mins Late',
      pointsSpent: 100,
      status: 'fulfilled',
      requestedAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
      resolvedAt: new Date(Date.now() - 71 * 3600 * 1000).toISOString(),
      parentNote: 'Watched Friday cartoon',
    },
  ],
  settings: {
    parentPin: '1234',
    currencyName: 'Points',
    currencySymbol: '⭐',
    soundEnabled: true,
    requireApprovalForTasks: false,
    unraidHostName: 'unraid.local:3000',
  },
};
